// <auto-generated />
namespace WebApplication_task1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class added_mark_tabke : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_mark_tabke));
        
        string IMigrationMetadata.Id
        {
            get { return "202301090904087_added_mark_tabke"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
